%%%
%%% createLAYERSSIZEh.m
%%%
%%% Generates the MITgcm file LAYERS_SIZE.h from specified array
%%% dimension parameters.
%%%

function createLAYERSSIZEh (dirname,Nlayers,layers_maxNum)

  layerssizehtext = [...    
    'C ======================================================================\n', ...    
    'C * Compiled-in size options for the LAYERS package *\n', ...    
    'C\n', ...    
    'C  - Just as you have to define Nr in SIZE.h, you must define the number\n', ...    
    'C    of vertical layers for isopycnal averaging so that the proper array\n', ...    
    'C    sizes can be declared in the LAYERS.h header file.\n', ...    
    'C\n', ...    
    'C  - Variables -\n', ...    
    'C        NLayers      :: the number if isopycnal layers (must match data.layers)\n', ...    
    'C        FineGridFact :: how many fine-grid cells per dF cell\n', ...    
    'C        FineGridMax  :: the number of points in the finer vertical grid\n', ...    
    'C                         used for interpolation\n', ...    
    '      INTEGER    Nlayers, FineGridFact, FineGridMax, layers_maxNum\n', ...    
    '      PARAMETER( Nlayers = ',num2str(Nlayers),' )\n', ...    
    '      PARAMETER( FineGridFact = 10 )\n', ...    
    '      PARAMETER( FineGridMax = Nr * FineGridFact )\n', ...   
    '      PARAMETER( layers_maxNum = ',num2str(layers_maxNum),' )\n',...
    ' \n'];
    
    fid = fopen(fullfile(dirname,'LAYERS_SIZE.h'),'w');
    if (fid == -1)
      error('Could not open LAYERS_SIZE.h');
    end
    fprintf(fid,layerssizehtext);
    fclose(fid);
    
end