%%%
%%% create_eedata.m
%%%
%%% Generates the MITgcm required file eedata.
%%%
function create_eedata (dirname,listterm,nTx,nTy)  
  
  %%% Main function of eedata file is to set the number of threads per
  %%% process in the x- and y- directions. Typically nTx=nSx and nTy=nSy,
  %%% so that each process handles nSx*nSy tiles, each with its own thread.
  eedatatext = [...
    '# "eedata" file \r\n' ...
    '# Lines beginning "#" are comments \r\n' ...
    '# nTx - No. threads per process in X \r\n' ...
    '# nTy - No. threads per process in Y \r\n' ...
    ' &EEPARMS \r\n' ...
    ' nTx=',num2str(nTx),', \r\n' ...
    ' nTy=',num2str(nTy),', \r\n' ...    
    ' ',listterm,' \r\n' ...
    '# Note: Some systems use & as the namelist terminator (as shown here). \r\n' ...
    '#       Other systems use a / character.'];
    
  fid = fopen(fullfile(dirname,'eedata'),'w');
  if (fid == -1)
    error('Could not open eedata file');
  end
  fprintf(fid,eedatatext);
  fclose(fid);
    
end